info:
  name: sample-service
  version: ${PROJECT_VERSION:0.0.1-SNAPSHOT}
  description: description

server:
  port: 8080
  tomcat:
    acceptCount: 1024
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
  servlet:
    context-path: /sample-micro-service

spring:
  main:
    bannerMode: "OFF"
  #    allow-bean-definition-overriding: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      USE_BIG_DECIMAL_FOR_FLOATS: true
    default-property-inclusion: non_null

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, WARNING, UNKNOWN, UP
    web:
      server:
        auto-time-requests: true
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /sample-micro-service/management
      exposure:
        include: health, info, prometheus

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html